### PR TITLE
Respect checkAccess for total resolver

### PR DESCRIPTION
**Pull request by justinr1234**

### CODE REVIEW

**Comment by SachaG** [comment]
Btw I wonder if it would make more sense to get rid of the Total resolver and have the list resolver return an object with both `results` and `total` fields? Maybe at some point we should take another look at that part of the API.

**Comment by justinr1234** [comment]
Maybe, but in that case you can just do `results.length`

**Comment by SachaG** [comment]
Well no because `results.length` gives you the number of results currently loaded, while `total` gives you the *total* count for matching results in your db (i.e. could be a hundred thousand).

**Comment by justinr1234** [comment]
Good call, that could make the most sense.

**Pull request merged**
