### PR TITLE
Fix circular dependencies between schemas and collections

### PR DESCRIPTION
**Pull request by justinr1234**
`collection.js` is importing `schema.js` for `createCollection` but `schema.js` is importing `collection.js` for varying runtime function definitions resulting in undefined circular load order on files.

### CODE REVIEW

**Comment by MHerszak** [comment]
Nice! While you are at it. How about a little warning in case you cant find a collection? Find returns 'undefined' and will break it 💯

**Comment by justinr1234** [comment]
@MHerszak I would assert it should break in that case. Thoughts?

**Comment by MHerszak** [comment]
you could just add console.error ;)

**Comment by justinr1234** [comment]
Leaving it would allow the stack trace to print out properly showing where it failed and triggering someone to realize they misspelled it. I'm still asserting not to catch the error!!!!!!

**Comment by MHerszak** [comment]
This might be good to be included as props like `collectionName` for SmartForms as well.

**Comment by justinr1234** [comment]
@MHerszak https://github.com/VulcanJS/Vulcan/pull/1840

**Comment by SachaG** [comment]
Thanks!

**Pull request merged**
