### PR TITLE
Changed to import PropTypes from 'prop-types';

### PR DESCRIPTION
**Pull request by MHerszak**
I added import PropTypes from 'prop-types'; Oh, don't forget to do a npm install.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! But I think you need to merge into devel, not in master?

**Comment by MHerszak** [comment]
@SachaG I am a bit confused. For whom is your comment?

**Comment by SachaG** [comment]
Oh wait did I merge this? Hmm I think that was a mistake on my part… Hopefully it doesn't matter too much, but I meant that you made the PR to `master` instead of `devel`.

**Comment by MHerszak** [comment]
@SachaG my pull request was to devel not Master. That was another reason why I was confused. Also, none of my changes is merged. Wanna do this again?

**Comment by SachaG** [comment]
Yeah I think you better do another PR based on the latest devel. Not sure what happened here…

**Pull request merged**
