### PR TITLE
add minCount and maxCount to SmartForm nested arrays

### PR DESCRIPTION
**Pull request by Neobii**
This allows you to supply minCount and maxCount on the form fields.

Supplying min count will automatically add nested form fields.

Hides ui when max and min are reached.

#2138

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! That looks like a good implementation. I assume validation is already taken care of by SimpleSchema on the server?

**Comment by SachaG** [comment]
My only worry is whether creating empty documents can somehow mess things up. And edge cases like what would happen if a field is not required, but does have a `minCount`. But we can probably deal with that if/when it becomes an issue. 

Also I wonder if maybe we should display a counter (e.g. `2/3`) somewhere so that people understand why the "add item" button disappears when you reach the max. That can be a separate PR though.

**Comment by Neobii** [comment]
I can work on that edge case, as for the counter do you think it should be optional to display?

**Comment by Neobii** [comment]
The counter might not make sense when you specify minCount because that will populate 2 empty fields and the count would already show `minCount/maxCount`

**Comment by SachaG** [comment]
Yeah I'm not sure about the counter, I haven't needed this feature yet myself so I'm not sure what makes the most sense. Let's use this as a start and improve it later :)

**Pull request merged**
