### PR TITLE
feature/update react-helmet

### PR DESCRIPTION
**Pull request by kevinashworth**
The NFL has released version 6.0.0 of react-helmet. It has one breaking change re named import/export: https://github.com/nfl/react-helmet/wiki/Upgrade-from-5.x.x----6.x.x-beta

### CODE REVIEW

**Comment by eric-burel** [comment]
Thanks! Could you please also check for the Starter for the same update?

**Comment by kevinashworth** [comment]
On it.

**Comment by kevinashworth** [comment]
cf https://github.com/VulcanJS/Vulcan-Starter/pull/168

**Comment by eric-burel** [comment]
Awesome thank you

**Pull request merged**
