### PR TITLE
Datatable - replace SPACE with - in the datatable-item-* className

### PR DESCRIPTION
**Pull request by vincro**
Currently column names such as "Company Name" for example that do not exist in schema get converted to:

`datatable-item-company name`

rather than being converted to:

`datatable-item-company-name`

### CODE REVIEW

**Comment by SachaG** [comment]
Nice. But I might be wrong, but doesn't `replace` only replace the first instance of a string? So there would still be cases where it doesn't work?

**Comment by justinr1234** [comment]
Yes it only does the first letter. Need a regex replace for multiple.

**Comment by vincro** [comment]
Indeed you are correct.  I will fix and push change.

**Comment by SachaG** [comment]
Nice work :)

**Pull request merged**
