### PR TITLE
Move mutations.test to the client side

### PR DESCRIPTION
**Pull request by yannick-mayeur**
This has to be done on the client side because on the server side we do not have access to a full client with a cache.
Linked to #2415.

### CODE REVIEW

**Comment by eric-burel** [comment]
You probably should keep most of the test on both client and server actually, only tests related to `multiQueryUpdater` are to be moved only client side.

**Comment by yannick-mayeur** [comment]
I have updated this to only move the correct tests. The client side tests are still failing though.

**Comment by eric-burel** [comment]
Can you show the error message for client side test? You may have something either in the server console or the browser console

**Comment by eric-burel** [comment]
I think we can merge this already if you remove the "Draft" state (I can't change it myself), and you can  open another PR for your fixes and improvements later

**Comment by yannick-mayeur** [comment]
The error I have is the same I already wrote about in the issue: https://github.com/VulcanJS/Vulcan/issues/2415#issuecomment-566570429

**Comment by eric-burel** [comment]
Fixed and merged, thanks a lot!

**Pull request merged**
