### PR TITLE
Unit Testing Update

### PR DESCRIPTION
**Pull request by ErikDakoda**
* Got client unit tests running
 * Upgraded to Meteor 1.8.1
 * Added a custom version of meteortesting:mocha package - the only way to get it to use meteortesting:mocha-core@6.1.2, meteortesting:browser-tests@1.2.0, and lmieulet:meteor-coverage@3.2.0
 * Updated some client unit tests to get them to pass
 * Made experimental change to mutators.test.js - client tests would not run when the Foo2s collection is initialized inside before()

### CODE REVIEW

**Comment by ErikDakoda** [comment]
Hi @eric-burel! I have been working on unit testing my own code base and I wanted to incorporate a lot of what I learned into Vulcan. Most client tests are passing, but not all. Please have a look, and you are welcome to scrap this pull request if you think I am going in the wrong direction.

**Comment by eric-burel** [comment]
Awesome! That's great news, I'll give it a shot as soon as I can work back on Vulcan, I think next week. No I think you are heading to the correct direction, testing is just inherently hard to setup with Meteor currently.

I've indeed have a few issues with collection, I could'nt manage to create collections just for one test because I can't drop them, so it may raise a few issues.

**Comment by eric-burel** [comment]
When just running tests, I've got this long error:
```
--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
=> Client modified -- refreshing (x3)
=> Client modified -- refreshing (x5)
/code/Vulcan/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

WebDriverError: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.18.0-25-generic x86_64)
    at Object.checkLegacyResponse (/code/Vulcan/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/code/Vulcan/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/code/Vulcan/node_modules/selenium-webdriver/lib/http.js:441:30)
    at /home/eric-burel/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

From: Task: WebDriver.createSession()
    at Function.createSession (/code/Vulcan/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/code/Vulcan/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/code/Vulcan/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/code/Vulcan/node_modules/selenium-webdriver/index.js:642:16)
    at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:54:136)
    at startBrowser (packages/meteortesting:browser-tests/server.js:27:7)
    at clientTests (packages/meteortesting:mocha/server.js:140:3)
    at serverTests (packages/meteortesting:mocha/server.js:185:7)
    at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:120:13)
    at done (/home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/mocha.js:838:7)
    at Runner.<anonymous> (/home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:918:5)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:903:12
    at /home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:772:9
    at next (/home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:362:14)
    at Immediate._onImmediate (/home/eric-burel/.meteor/packages/meteortesting_mocha-core/.6.1.2.14anf49.f69m++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mocha/lib/runner.js:425:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

=> Client modified -- refreshing(node:5071) UnhandledPromiseRejectionWarning: Error: process exited
    at ChildProcess.otherProcess.on (packages/inter-process-messaging.js:212:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

 => awaited here:
    at Function.Promise.await (/home/eric-burel/.meteor/packages/static-html/.1.2.2.10bnogu.urs6h++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at Promise.asyncApply (/tools/runners/run-app.js:810:7)
    at /home/eric-burel/.meteor/packages/static-html/.1.2.2.10bnogu.urs6h++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
(node:5071) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eric-burel** [comment]
@ErikDakoda can you please run this command and tell me if it's ok to you: `TEST_SERVER=0 TEST_CHROME_ARGS="--no-sandbox --–disable-dev-shm-usage" TEST_BROWSER_DRIVER=chrome meteor test-packages ./packages/* --port 60859 --driver-package meteortesting:mocha --raw-logs`

I seem to have smth working with those additional args for Chrome. 
The tests themselves aren't passing yet for me but that's not an install problem anymore, we just need to update them I think

**Comment by ErikDakoda** [comment]
@eric-burel I ran that command and it ran the client tests fine (other than some warnings) with "12 passing (54ms)". Without `TEST_SERVER=0` the server tests run, but the client tests fail with an error.

As far as reports, maybe this is what you are looking for: https://github.com/meteortesting/meteor-mocha/blob/master/README.md#write-tests-to-a-file

**Comment by eric-burel** [comment]
I still have weird behaviour, it seems to be a `chromedriver` configuration issue. The errors only display once in a while that's why I have trouble debugging. Related: https://github.com/heroku/heroku-buildpack-google-chrome/issues/46

First my version of Chromedriver does not seem to be correct, it may be better to force it to use a relevant for your OS during install.
For me on Ubuntu with Chromium: `npm install chromedriver --chromedriver_filepath=$(which chromium.chromedriver)`
It's better but still not fixed, I'll keep documenting my progression

@ErikDakoda what is your version of chrome and OS? Do you use chromium?

**Comment by eric-burel** [comment]
I still have weird behaviour, it seems to be a `chromedriver` configuration issue. The errors only display once in a while that's why I have trouble debugging. Related: https://github.com/heroku/heroku-buildpack-google-chrome/issues/46

First my version of Chromedriver does not seem to be correct, it may be better to force it to use a relevant for your OS during install.
For me on Ubuntu with Chromium: `npm install chromedriver --chromedriver_filepath=$(which chromium.chromedriver)`
It's better but still not fixed, I'll keep documenting my progression

@ErikDakoda what is your version of chrome and OS? Do you use chromium?

**Comment by eric-burel** [comment]
Eventually... So I am going to document the process here, we may create a cleaner doc later:

## Test

Run `meteor npm install` to install chromedriver and selenium (of course having Chrome or Chromium on your computer).
Run `npm run test-unit`. Server side tests should always run ok. 
**Verify that client side tests are working too**.

If they don't, go to next step.

## Check your chrome driver install

The `chromedriver` [Node wrapper package](https://www.npmjs.com/package/chromedriver) will automatically download the actual driver for you. But sometimes that's not the right version.

In this case, [download manually the correct driver](http://chromedriver.chromium.org/), and use the command:
```
npm install chromedriver --chromedriver_filepath="path-to-relevant-zip"
```
You can also put this variable in your `.npmrc` (see `node-chromedriver` doc for all details).

## Not yet solved?

You can sometimes encounter the [DevToolsActivePort file doesn't exist issue](https://github.com/heroku/heroku-buildpack-google-chrome/issues/46), which means that your app failed to connect to an instance of Chrome.

Run the test command with an additional arg to change the connection port:
```
TEST_CHROME_ARGS="--remote-debugging-port=9222" TEST_BROWSER_DRIVER=chrome meteor test-packages ./packages/* --port 60859 --driver-package meteortesting:mocha --raw-logs
```

---
So  @ErikDakoda I am soliciting you again, can you  please run `TEST_CHROME_ARGS="--remote-debugging-port=9222" TEST_BROWSER_DRIVER=chrome meteor test-packages ./packages/* --port 60859 --driver-package meteortesting:mocha`?

If it's ok for you I'll be able to fix the failing tests and eventually merge. That means we will eventually have client side unit tests, that's cool for some difficult features.

Also, besides unit tests, we could benefit from installing Cypress at app level, it seems to be a good e2e framework.

**Comment by ErikDakoda** [comment]
@eric-burel I am on MacOS and running the latest Chrome, which currently is 75.0.3770.142

**Comment by ErikDakoda** [comment]
@eric-burel I ran `TEST_CHROME_ARGS="--remote-debugging-port=9222" TEST_BROWSER_DRIVER=chrome meteor test-packages ./packages/* --port 60859 --driver-package meteortesting:mocha` and it ran fine on both server and client, with most tests passing.

**Comment by ErikDakoda** [comment]
@eric-burel FYI I started a page in the docs about unit testing: https://github.com/VulcanJS/vulcan-docs/pull/126

This is as far as I got so far, but I am committing it so that you can review and update it.

**Comment by eric-burel** [comment]
Awesome PR, thanks a lot! Now time to review the Storybook PR :)

**Comment by eric-burel** [comment]
Hmm it's broken again for me but... if I remove all references to chrome and simply open the test app, I get client side tests to work (http://localhost:60859/).

Mocha works in mysterious ways.

**Pull request merged**
