### PR TITLE
Fix example-forum events callback

### PR DESCRIPTION
**Pull request by justinr1234**

### CODE REVIEW

**Comment by SachaG** [comment]
Why would that trigger an error? If the event doesn't exist wouldn't `existingClickEvent` just be `undefined`?

**Comment by justinr1234** [comment]
I think the code is wrong altogether. `vulcan-events` doesn't export a collection.

**Comment by SachaG** [comment]
Ohh right I did change that. Yeah this would need a refactoring to use `track`. And maybe we then add a `unique: true` option to `track` to make it check for existing events first.

**Comment by justinr1234** [comment]
For the time being this fixes it, but it isn't the right fix long term. I don't have time to mess with fixing it right at the moment!

**Comment by SachaG** [comment]
ok

**Pull request merged**
