### PR TITLE
Feature/backoffice

### PR DESCRIPTION
**Pull request by Julien-Sytadelle**
Merged lastest devel 1.13.0
copied column name generation for CollectionList component from original vulcan-backoffice-builder.

### CODE REVIEW

**Comment by eric-burel** [comment]
Do you have a working version?

I am planning to finish up this feature, but currently I simply lack a left menu layout component for both Bootstrap and Material UI, in order to display all available collections in a single menu. 
I somehow fell into a rabbit hole because I wanted to use Storybook to develop this component, and then I wanted to put Material UI into the core to test Storybook... and here al I.

**Comment by Julien-Sytadelle** [comment]
Hi,

Thanks to your directions I could update to 1.13.0 and everything works.
It just generates the columns datatable property that was missing as you did.
There is no actions generation else default edit but it is enought for now.

I plan to make a material-ui Layout replacing VulcanBackofficeLayout, something very simple at first.

**Comment by enzolutions** [comment]
@Julien-Sytadelle could you share some screenshots about what deal new feature delivery?

**Comment by Julien-Sytadelle** [comment]
It simply automatically adds a route to a list and an item for each registered collection using function registerBackoffice.

Then, once you set up a new collection you can directly interact with it and even reuse the component for quick prototyping. 

Have a look at admin part of awesome-vulcan app from Eric.
Ex: https://www.awesome-vulcan.com/admin/articles

Le 16 avr. 2019 à 22:00, à 22:00, enzo - Eduardo Garcia <notifications@github.com> a écrit:

**Comment by eric-burel** [comment]
@Julien-Sytadelle Regarding the material UI layout [I've built this one](https://github.com/lbke/vulcan-more-material-ui/tree/master/lib/components/layouts) based on Erik Dakoda's version. It is responsive .
It's the more the Bootstrap part that lacks now.

**Comment by Julien-Sytadelle** [comment]
Hi,
I know, I used it as base start. Works great. 
Thanks for this also.


Le 18 avr. 2019 à 11:33, à 11:33, Eric Burel <notifications@github.com> a écrit:

**Pull request merged**
