### PR TITLE
Fixed voting bugs

### PR DESCRIPTION
**Pull request by Discordius**
This PR fixes two bugs in voting: 

1. Voting doesn't properly update the score and the active status of an item
2. Cancelling a vote deletes *all* votes from an item, not just your own

### CODE REVIEW

**Comment by MHerszak** [comment]
Hi, great work! Do you mind adding pull request to the devel branch?

**Comment by SachaG** [comment]
Oh right, new PRs should be made to `devel`.

**Comment by Discordius** [comment]
Done, sorry for that.

**Comment by SachaG** [comment]
👍

**Pull request merged**
