### PR TITLE
Added error for unregistered fragments

### PR DESCRIPTION
**Pull request by MHerszak**
I had a fragment not registered. Setting an error to make sure which one is missing is good for debugging.

### CODE REVIEW

**Comment by MHerszak** [comment]
If you merge make sure to add Emails component in the debug package. I commented it out and did not reverse it. This will create issues when you use the debug package and rely on Emails component.

**Comment by SachaG** [comment]
Thanks! But do you think you could submit a PR that only contains the commit relevant to this specific issue?

**Comment by MHerszak** [comment]
How can I add individual pull requests? Every time I push a change and I want to add another pull request the only option is no option to add another pull request. Is there something I should consider before submitting the pull request?

**Comment by SachaG** [comment]
Here's what I would do:

1) fork the Vulcan repo
2) make the changes you want
3) commit only the relevant files
4) push back to your github remote
5) submit PR

**Pull request closed without merging**
