### PR TITLE
Bug (#1767): Set good work dir before copying sample_settings.json

### PR DESCRIPTION
**Pull request by martinhbramwell**
This adds a simple function to determine the real project source root directory before trying to copy sample_settings.json.

### CODE REVIEW

**Comment by MHerszak** [comment]
@martinhbramwell my question is why is it necessary to copy the file in the first place. What is the use case?

**Comment by martinhbramwell** [comment]
As far as I can see, the only purpose is to ensure a problem free start up experience for new users, as we all know and love about Meteor. From that viewpoint, the bug is much worse than the problem it's meant to solve. I did get it doing what it's meant to do, but I have seen that the sample settings cause the "newsletter" module to make Vulcan fail horrendously and  incomprehensibly. I've been trying to get to know Vulcan, but find I am constantly tripped up by surprise problems, hence my three PRs to date, and another on the way. I want to see Vulcan get really popular, but it won't with the current getting started experience.

**Comment by SachaG** [comment]
What does `wrk_dir = '../../../../..';` do here? How are you determining this path?

**Comment by martinhbramwell** [comment]
There are two possible locations from which the script can execute, which I really don't expect will ever change: the root of the project and the root of Meteor's run time of the project.  The latter is 5 levels below the former, so ```wrk_dir``` simply points back up to the top where the file is sure to be found.

**Comment by SachaG** [comment]
Why would the script execute from two locations though? If that script doesn't behave in an understandable way, we might as well remove it.

**Comment by martinhbramwell** [comment]
I believe it executes from within Meteor's runtime directories because Meteor is aggressive about collecting all possible changes when a developer updates any file not prefixed with '.'

Evidently it uses `npm prestart` as part of its changes collection process, which means that you can alter stuff like 'sample_settings.json' and Meteor will reload it each time!

I see no point in copying 'sample_settings.json' over and over again, so perhaps a better solution is to copy it when : 

1. there's no `settings.json` and
1. the base path of the script is **not** in Meteor's run time directories

I can redo it like that if you want.

**Comment by martinhbramwell** [comment]
This PR would pull from the **wrong branch** in my fork.

Closed in favour of new PR  #1783

**Pull request closed without merging**
