### PR TITLE
Omit formState in AccountsSwitcher

### PR DESCRIPTION
**Pull request by MHerszak**
this.props and state both pushed formState.

### CODE REVIEW

**Comment by MHerszak** [comment]
The conflict is only a one-liner and can be deleted, which will resolve it.

**Comment by SachaG** [comment]
Wouldn't the formState from props just get overridden by the one from state? I don't know if the omit is necessary?

**Comment by MHerszak** [comment]
The later once are being overwritten is what the specifications say. I just don't believe it is good practice but it doesn't hurt either.

**Comment by SachaG** [comment]
Given that I want to scrap this whole accounts package anyway I think we can leave it for now.

**Pull request closed without merging**
