### PR TITLE
Allow registering component with unique argument without hocs

### PR DESCRIPTION
**Pull request by Apollinaire**
Before: 
```js
registerComponent({name: 'MoviesItem', component: MoviesItem});
```
would crash the app with the message `cannot read map of undefined`  because `getComponent` tried to map on `hocs`. 

Now, `hocs` is defaulted to `[]` in `registerComponent` to avoid adding the `hocs` property when you don't need it

### CODE REVIEW

**Comment by Apollinaire** [comment]
I added support for single argument on replaceComponent: `{name: 'MyComponent', component: NewComponent, hocs: [hoc1, [hoc2, option2]]}`
Might create conflicts with #2029 but they should be easy to resolve

**Comment by Apollinaire** [comment]
Resolved merge conflicts

**Comment by SachaG** [comment]
Sorry for not merging this earlier, somehow I missed it. But why is the same error duplicated?

**Comment by SachaG** [comment]
I'll refactor this to keep it a little bit DRYer :)

**Pull request closed without merging**
