### PR TITLE
Redux tests for setupRedux(initialState)

### LINKED ISSUE #2351: vulcan:redux does not handle initialState of createStore
When you initialize redux with vulcan:redux, the initialState is always empty.
PR #2350 add initialState in setupRedux and tests covering the feature

### PR DESCRIPTION
**Pull request by lc3t35**
this should close #2351

### CODE REVIEW

**Comment by GraemeFulton** [comment]
I've tested this in my own app, works great - [see here for guide](https://www.notion.so/Redux-for-Vulcan-b21807a78b574bee8bb6e93360165c2d).

**Comment by lc3t35** [comment]
@GraemeFulton great documentation, could you add a few lines about the initialState parameter in setupRedux ?

**Comment by eric-burel** [comment]
Awesome, glad you got it working. Does it provide a sufficient fix for your apps in the short run?

Regarding tests Erik Dakoda pushed a PR to improve testing and allow running client side tests. I started reviewing #2349 but I need a bit more time because some tests were not triggered as expected. 

Last time I checked vulcan:lib tests were passing but Meteor testing works in mysterious ways.

Can the Notion page be converted into markdown so we can add it to the official doc?

**Comment by GraemeFulton** [comment]
> @GraemeFulton great documentation, could you add a few lines about the initialState parameter in setupRedux ?

I've added the info about initialState parameter today, thanks again for this fix!

**Comment by eric-burel** [comment]
Hi, tests are passing fine for me, @GraemeFulton @lc3t35 is it fine to merge for you? Does it solve your issues with Redux?

**Comment by GraemeFulton** [comment]
hey it does solve my issue @eric-burel !

**Comment by yairtal** [comment]
I solves my issues as well, is there anything I can do to help get this merged?

**Comment by kevinashworth** [comment]
I use Redux. This change is very helpful to me, it's one that I keep pulling into my local Vulcan repo again and again. The 2 conflicting files can just be deleted. (I delete them after after every merge.) I'd like to see this PR merged into Vulcan.

**Comment by eric-burel** [comment]
Hi,

Do you think it would doable to avoid the explicit `setupRedux` call? Basically what bothers me is that you can't add values to the `initialState` from another package.

Instead, I'd rather have `setupRedux` be called automatically, maybe in a `Meteor.startup` function, and the initialState built from a callback, so that any package can add new parts to the initialState. 
It feels more "vulcanish" to me, in the sense that it would respect the package oriented architecture where any package can freely enhance the app.

That's why I did not merge it in the first place. However I am not sure what I expected would work, maybe it's an over-optimization. Would need @SachaG opinion on this.

**Comment by eric-burel** [comment]
Smth like: 
```
let store = null
export const getStore = () => store
const setupRedux = () => {
  const initialState = runCallbacks({name: 'redux.initialState', iterator: initialState}) // this part allow a package to enhance the initialState implicitely 
  store = initStore();
  addCallback('router.server.wrapper', function ReduxStoreProvider(app) {
    return <Provider store={store}>{app}</Provider>;
  });

Meteor.startup(() => setupRedux())
```

**Comment by lc3t35** [comment]
@eric-burel you mean `store = initStore(initialState);` ;)

**Pull request merged**
