### PR TITLE
GraphQL Subscriptions and Filters

### PR DESCRIPTION
**Pull request by Aetherall**
There is my implementation of subscriptions for vulcan

vulcan:lib/filters.js probably needs a refactor
filters list needs an upgrade

run `npm run start`
then go to [graphiQL Subscription](http://localhost:3000/graphiql?query=subscription%7B%0A%20%20Movies(filter%3A%7Bmutation_in%3A%5BCREATED%5D%7D)%7B%0A%20%20%20%20node%7B_id%7D%0A%20%20%7D%0A%7D) and [graphiQL Mutation](http://localhost:3000/graphiql?query=mutation%7B%0A%20%20MoviesNew(document%3A%7Bname%3A%22test%22%7D)%7B%0A%20%20%20%20_id%0A%20%20%7D%0A%7D)

### CODE REVIEW

**Comment by SachaG** [comment]
I don't really know anything about Apollo/GraphQL subscriptions, but that looks great! Maybe you could make a quick video walkthrough to explain the different aspects of the code?

Also I think it'd be great to have a separate `example-subscriptions` example package just to showcase this feature. What do you think?

**Comment by Aetherall** [comment]
For sure, I'm currently thinking about a withReactiveDocument HOC and withReactiveList HOC
then I will make the exemple maybe with a video walkthrough if my english allows me to do so

**Comment by comus** [comment]
https://github.com/apollographql/core-docs/pull/260#issuecomment-287215673
they said pubsub have some limit of listener.

**Comment by Aetherall** [comment]
@comus You're right, as said on [stackoverflow](https://stackoverflow.com/questions/43752073/graphql-subscriptions-max-listeners-exceeded-warning), graphql-subscription pubsub is not recommended for production, and it should be replaced.

However I feel like mongodb 3.6 can bring the solution with the notification API, so we may wait a little to see how it  will be handled by the node.js community

So a temporary workaround could be to raise up the limitation manually
```javascript
import { PubSub } from 'graphql-subscriptions';

const pubsub = new PubSub();
pubsub.ee.setMaxListeners(30); // raise max listeners in event emitter

export { pubsub };
```

**Comment by justinr1234** [comment]
@Aetherall What about taking it a step further and just implementing it using MQTT?

**Comment by Aetherall** [comment]
@justinr1234 My knowledge about those is too weak... And I don't have the time right now to dive in, so feel free :)

**Comment by justinr1234** [comment]
@Aetherall Can you possibly refactor this to fix the spacing that you changed? You changed spaces into tabs on several files and it makes reading the diff very difficult. You should be able to modify the package.json locally and add `--fix` the `lint` command and then run `npm run lint` and it should automatically fix most of the spacing issues. Additionally would you mind rebasing this?

I was planning to go through your changes more thoroughly and possibly implement some changes on top to allow us to swap subscription libraries automatically so that this is production ready out of the box.

**Comment by Aetherall** [comment]
Feel free to rebase this ! :) I am not using vulcanJs anymore and I would love to see that my work is usefull for Vulcan community
Do you still need me to lint the changes if you rebase it ?

**Comment by justinr1234** [comment]
I’ll just pick it up when I get a chance. Thanks!

**Pull request closed without merging**
