### PR TITLE
fix bug preflight from apollo

### PR DESCRIPTION
**Pull request by meteorplus**
resetStore: Store reset while query was in flight.

https://github.com/apollographql/apollo-client/issues/2919#issuecomment-378790109

### CODE REVIEW

**Comment by SachaG** [comment]
Oh nice! Glad we can finally get rid of that error!

**Comment by meteorplus** [comment]
you're welcome 🥇 now pay me in crypto :P

**Comment by SachaG** [comment]
I could give you half of all the Bitcoin I own, would that work?

**Comment by meteorplus** [comment]
@SachaG that's very generous! Deal!

**Comment by SachaG** [comment]
OK, here's zero Bitcoins :)

**Pull request merged**
