### PR TITLE
make Datatable edit modal title customizable

### PR DESCRIPTION
**Pull request by carloslfu**
As well as other modal properties

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks but I'm not sure I like the `_modalProps` variable name, we never use that naming style anywhere else in the codebase…

**Comment by carloslfu** [comment]
Yes, you are right, what do you think is a good name for it?

**Comment by SachaG** [comment]
You could have `defaultModalProps` and `customModalProps`? Also this is a little hard to read:

```
const _modalProps = { title: <code>{document._id}</code>, ...(_isFunction(modalProps) ? modalProps(document) : (modalProps || {})) };
```

I would write it as:

```
const { modalProps = {} } = props
```

And then:

```
const defaultModalProps = { title: <code>{document._id}</code> }
const customModalProps = { ...defaultModalProps, ...(_isFunction(modalProps) ? modalProps(document) : modalProps) };
```

Or something similar. What do you think?

**Comment by carloslfu** [comment]
It makes sense, thanks @SachaG. I'm gonna fix it.

**Comment by carloslfu** [comment]
It's done, what do you think?

**Comment by SachaG** [comment]
Looks good! Btw, is there a reason why you called the function `_isFunction` rather than just `isFunction`?

**Comment by carloslfu** [comment]
Is following the same convention as [_sortBy](https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-core/lib/modules/components/Datatable.jsx#L9) that comes from Lodash.

**Comment by SachaG** [comment]
Thanks for making all those changes! Nice work :)

**Pull request merged**
