### PR TITLE
center submit and cancel button

### PR DESCRIPTION
**Pull request by pravdomil**
**before**
before

**after**
after

### CODE REVIEW

**Comment by pravdomil** [comment]
@vincro yes you can do that but by default it should be in center or on right right side, I think that's how it's done in most forms on the internet, what do you think?

**Comment by justinr1234** [comment]
All a matter of personal preference, there is no standard way of doing it. Left aligned is probably the safest. Probably aligning it to the left side of the text boxes even.

**Comment by SachaG** [comment]
Thanks for the PR!

But yeah I'm not sure if the current alignment is the best, but centering feels even weirder. I'd rather leave it be and let people change their CSS if they want to, sorry :(

P.S. for future PRs, try to make them to the `devel` branch :)

**Comment by justinr1234** [comment]
There should be a way to default the repository settings to make PRs against devel

**Comment by pravdomil** [comment]
@SachaG change your default branch to `devel` in github repo settings

**Comment by SachaG** [comment]
Yes I agree on the right would probably be better. But I don't want to add extra styles at this point. Maybe in the future if we use Styled Components. 

And for the branch, if I do that it will also default to `devel` when people clone the repo, I'm not sure if that's what we want.

**Comment by pravdomil** [comment]
@SachaG that's how https://github.com/meteor/meteor done it (devel is their default branch)

**Comment by SachaG** [comment]
Yeah ok I guess we can do the same then.

**Comment by pravdomil** [comment]
@SachaG ok and center that button please

**Pull request closed without merging**
