### PR TITLE
Added support for Embed API

### PR DESCRIPTION
**Pull request by meteorplus**
Added support for Embed API depending on the key length
no need to add anything or change anything! not need to add any package just add ytour embed api key on embedlyKey : "your_key_here" and it will work right away

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! But it seems like doing things this way results in a lot of duplicate code. Maybe you could refactor the function so that it has better flow and is easier to understand?

**Comment by SachaG** [comment]
Oh also you definitely can't do `embedlyKey.length > 32`, that's way too hacky! Please use a separate setting name :)

**Comment by meteorplus** [comment]
ok thanks :)

I will clean it up and refactor it

**Comment by meteorplus** [comment]
okay cleaned it up and made a different file for the embed api call

**Comment by SachaG** [comment]
Won't this throw an error if people have no Embedly or EmbedAPI keys at all?

**Comment by SachaG** [comment]
I think you should rethink the code organization a little bit. Try to write it in a way that will also be easy to extend in the future if people want to add a third similar service.

**Comment by SachaG** [comment]
Actually I'll refactor the package myself in a way that makes it possible to add additional services. Once I'm done you can make another PR to integrate EmbedAPI cleanly :)

**Pull request closed without merging**
