### PR TITLE
Bug (#1669): Wait for users to exist before referring to them

### PR DESCRIPTION
**Pull request by martinhbramwell**
Fixes issue #1669.
Adds a simple wait loop in each example module to ensure initial start up proceeds without breaking.

### CODE REVIEW

**Comment by SachaG** [comment]
I understand the issue but this doesn't seem like a good fix… Isn't there a cleaner way?

**Comment by SachaG** [comment]
Also I would've thought the fact that Meteor uses Fibers would take care of race conditions like this? Isn't it supposed to ensure everything runs in the right order?

**Comment by justinr1234** [comment]
The proper solution would be in this file: https://github.com/VulcanJS/Vulcan/blob/master/packages/example-forum/lib/server/seed/seed_posts.js

```
import { Promise } from 'meteor/promise';

// ...

  const createUser = function (username, email) {
    const user = {
      username,
      email,
      isDummy: true
    };
    return Promise.await(newMutation({
      collection: Users, 
      document: user,
      validate: false
    }));
  }

```

This would cause any call to `createUser` to wait in the Meteor Fibers as @SachaG has mentioned.

**Comment by justinr1234** [comment]
Fixed here: https://github.com/VulcanJS/Vulcan/pull/1849

**Pull request closed without merging**
