### PR TITLE
fix call to sortBy in Datatable.jsx

### PR DESCRIPTION
**Pull request by yairtal**
With out this dot the app will crash with an error

### CODE REVIEW

**Comment by eric-burel** [comment]
Hi, can you give a shot at my commit? Using `_.sortBy` with Underscore should be deprecated in favour to explicitely import functions from Lodash. Otherwise you end up with a zillion ko imports of Underscore + a dependency to magic global variables, it's a source of bug in Meteor apps

**Comment by yairtal** [comment]
app crashes with the following error:

```
ReferenceError: sortedColumns is not defined
at getColumns (packages/vulcan:ui-material/lib/components/core/Datatable.jsx:267:5)
at DatatableContents (packages/vulcan:ui-material/lib/components/core/Datatable.jsx:328:23)
```

**Comment by yairtal** [comment]
fixed it, works fine

**Comment by eric-burel** [comment]
My bad I deleted it (tried to update the file from Github UI...).
Thanks!

**Pull request merged**
