### PR TITLE
ReactDOM.hydrate() may not be defined for everyone

### PR DESCRIPTION
**Pull request by MHerszak**
ReactDOM.hydrate() may not be defined for everyone, it will now use hydrate if it is defined or fallback to render

### CODE REVIEW

**Comment by SachaG** [comment]
Why would it not be defined for everyone?

**Comment by MHerszak** [comment]
I am running React, and ReactDom on version 15. and not 16. Hydrate seems to be a feature of 16.x

**Comment by SachaG** [comment]
But we're also upgrading to React 16 anyway?

**Comment by MHerszak** [comment]
Yeah. I just thought I don't want to force others to update as well. This can be taken out after a while.

**Comment by SachaG** [comment]
But don't we *want* everybody to be on the same version of React? Handling multiple versions at the same time seems like a recipe for issues…

**Comment by MHerszak** [comment]
Okay, will close this pull request.

**Pull request closed without merging**
