### PR TITLE
Clean document/data in default mutators.

### PR DESCRIPTION
**Pull request by vale981**
Makes submission of dates possible, as the clean function converts types!

I am not entirely sure if this is the right place to put it, but hey, it works and I didn't want to chain it in more centrally, as checking is not always desired.

(Maye we should make checking optional?)

### CODE REVIEW

**Comment by SachaG** [comment]
Oh so you mean if you submit a date string for a `Date` field for example? I suspect in that case the GraphQL layer would still throw an error though… 

Generally I'm a bit hesitant to add any "magic" cleaning step that might modify documents into something the user doesn't necessarily expect so I'm not 100% sure about that to be honest. What if we just let user add it in a callback instead? Maybe make it easier by passing the schema as a callback option?

**Comment by vale981** [comment]
Graphql doesn't complain. I did open this PR because I need it for submitting dates with autoform and i didn't want to write a helper for every date field.

**Comment by vale981** [comment]
Good idea with that callback. The schema already is part of the context if I am not mistaken.

**Comment by SachaG** [comment]
Actually it wasn't, but I just added it.

**Comment by vale981** [comment]
Is this still relevant?

**Comment by SachaG** [comment]
No, I think we can close it.

**Pull request closed without merging**
