### PR TITLE
Missing es-ES translation

### PR DESCRIPTION
**Pull request by PolGuixe**
Disclaimer: I haven't tested all the translation deeply. 

I found one missing.

### CODE REVIEW

**Comment by SachaG** [comment]
Btw in the future please make all PRs to the `devel` branch :)

**Comment by vincro** [comment]
@SachaG como se dice en espanõl?

**Comment by PolGuixe** [comment]
@SachaG thanks for the heads up! 👍 I was just going too fast 😝 

@vincro que necessitas?

**Comment by vincro** [comment]
@PolGuixe just pulling Sasha's leg.

**Comment by SachaG** [comment]
Lo siento mucho, pero no hablo español…

**Pull request merged**
