### PR TITLE
Fix error on invalid form submit.

### PR DESCRIPTION
**Pull request by vale981**
When a smart form had errors and was submitted again it let to a problem with accessing `mutation.result.data[mutationName].data`.

This PR adds a little tweak and now it seems to work alright.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! But maybe using https://lodash.com/docs/4.17.10#get would make it cleaner? Not a big deal though, I can merge this as it is otherwise.

**Comment by vale981** [comment]
Yeah. I did not know about this ^^.

**Comment by SachaG** [comment]
Shouldn't it be

```
get(mutation, `result.data[${mutationName}].data`, {})
```

rather than

```
get(mutation, `result.data['${mutationName}'.data]`, {})
```

?

Also I think the `'` inside the path are unnnecessary.

**Comment by vale981** [comment]
This has become irrelevant if i am not mistaken.

**Pull request closed without merging**
