### PR TITLE
Fix nested field specifiers for forms.

### PR DESCRIPTION
**Pull request by vale981**
Specifying fields for nested schemas did not work.
This PR should fix the issue relatively elegantly.

### Examples:
```jsx
 <Components.SmartForm
                 collectionName="Users"
                 fields={['userProfile', 'userProfile.title']}
                 documentId={this.props.currentUser._id} />;
```
Selects the `userPofile.title` field to be displayed in the form. 

```jsx
 <Components.SmartForm
                 collectionName="Users"
                 fields={['userProfile']}
                 documentId={this.props.currentUser._id} />;
```
Renders all the subfields of `userProfile`.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks, that's a good idea! But to clarify, this means "show all subfields":

```
fields={['userProfile']}
```

And this means "show only userProfile.title":

```
fields={['userProfile.title']}
```

But what about this?

```
fields={['userProfile', 'userProfile.title']}
```

It seems like it could be interpreted either way?

**Comment by vale981** [comment]
`fields={['userProfile.title']}` would be invalid with this code

**Comment by SachaG** [comment]
I'm not sure, what makes the most sense? I think personally I would expect `fields={['userProfile.title']}` to work and show the `title` field, and `fields={['userProfile', 'userProfile.title']}` to show all subfields (so basically ignore `userProfile.title`). 

Also since this might potentially break how forms work and I'll need some time to test it out I might delay merging it until the current `devel` is merged and release, just so you know.

**Comment by vale981** [comment]
i am going to create a new PR with this functionality

**Comment by vale981** [comment]
See #2260

**Pull request closed without merging**
