### PR TITLE
CircleCI Config

### PR DESCRIPTION
**Pull request by luhagel**
Alright, this should enable us to run CircleCI with every build/pr/whatnot.
Right now, it's only running the linter, more to come.

_Already using a container with jdk in order to enable webdrivers in the future._

### CODE REVIEW

**Comment by luhagel** [comment]
While we're at it, I'm not allowed to enable CircleCI for Vulcan, so that'd need @SachaG 's input

**Comment by justinr1234** [comment]
@luhagel Thanks for this. Can you add comments to the circle CI file to explain what the different lines are doing? It's a bit confusing for Circle CI newbies like myself.

**Comment by SachaG** [comment]
> While we're at it, I'm not allowed to enable CircleCI for Vulcan, so that'd need @SachaG 's input

How do I do that?

**Comment by luhagel** [comment]
@justinr1234 sure thing
@SachaG Go to circleci.com, log in with github, select the vulcanjs org on the top left and add Vulcan as a project ;)

**Pull request merged**
