### PR TITLE
remove LinkContainer it breaks the react boostrap

### PR DESCRIPTION
**Pull request by meteorplus**
Using href of MenuItem instead of LinkContainer since it break react boostrap design!

### CODE REVIEW

**Comment by SachaG** [comment]
How does it break it? Also, if we don't use LinkContainer I don't know if React Router will work?

**Comment by meteorplus** [comment]
It breaks the the react boostrap behavior and css classes! the NavItem is already an a tag so the react router will pick it up!

**Comment by SachaG** [comment]
I thought React Router only picked up Link tag, not regular a tags?

**Comment by justinr1234** [comment]
This is outdated.

But for the sake of argument, you would override `onClick`. As @SachaG mentioned, the `<LinkContainer>` is meant to allow integration with `react-router` specifically so that we can do `history.push` behind the scenes. `<LinkContainer>` is a wrapper around `<Link>` that comes from `react-router`. Using a straight `href` will cause the page to reload, which breaks the Single Page Application design of Vulcan.

**Pull request closed without merging**
