### PR TITLE
Fix withDocument

### PR DESCRIPTION
**Pull request by MHerszak**

### CODE REVIEW

**Comment by SachaG** [comment]
That doesn't seem right?

**Comment by SachaG** [comment]
That doesn't seem right?

**Comment by MHerszak** [comment]
The collection wasn't defined when it reached line 10 'undefined'. How do you mean?

**Comment by MHerszak** [comment]
@SachaG I just check 'Consolidate getCollection code' same fix for withList.

**Comment by SachaG** [comment]
OK, but I meant including 4 commits in the PR? I'll fix it myself.

**Pull request closed without merging**
