### PR TITLE
Remove root element from SSR

### PR DESCRIPTION
**Pull request by yannick-mayeur**
This has to be done because is also added by the Start.jsx file.

### CODE REVIEW

**Comment by eric-burel** [comment]
Thanks, does it work both with SSR and without SSR? You don't have any SSR errors?
Also, are the tests from "packages/vulcan-lib/test/server/apollo-ssr.test.js" still ok? The one that checks `expect(sink.result.body).toMatch('<div id="react-app">');` might probably be deleted after your PR.

**Comment by yannick-mayeur** [comment]
How can I deactivate SSR to test locally if it still works?

**Comment by eric-burel** [comment]
@yannick-mayeur you did smth similar to debug the double head tag, you can disable SSR through a setting in `settings.json` (I can't remember exactly but you'll find it easily, smth like apolloServer.disableSsr)

**Comment by yannick-mayeur** [comment]
Oh yeah I remember doing something like that. I will try to find out what I did exactly.

**Comment by yannick-mayeur** [comment]
Okay this solution does not seem to be the right one. When testing with the `getting-started` package from the Starter, I have no `react-app` when it is not applied by the SSR. The better solution is probably https://github.com/VulcanJS/Vulcan/pull/2204.

**Comment by eric-burel** [comment]
Yeah it's not exactly the same behaviour, can you please give #2204 a shot and tell me if it's mergeable?

**Comment by eric-burel** [comment]
Closing in the meantime

**Comment by yannick-mayeur** [comment]
I am not able to reproduce the bug of having two root elements in the application. But it does not crash the application nor completely remove `react-app`.

**Pull request closed without merging**
