### PR TITLE
vulcan-events: fix TypeError: Cannot redefine property: name

### PR DESCRIPTION
**Pull request by calinn**
google analitycs and vulcan-events get error so google bot from google search console can't load rest resource to render web page

### CODE REVIEW

**Comment by calinn** [comment]
I think it resolve it:
https://github.com/emberjs/ember.js/issues/4567#issuecomment-38351180

**Comment by SachaG** [comment]
`f2 = {...f2};` seems a bit hacky? Maybe you could use lodash's `clone`, or at least add some comments to make it clearer what's going on?

**Comment by calinn** [comment]
I'm cloning it to make a copy of f2, because f2 already has a 'name' attribute from f

**Comment by SachaG** [comment]
But f2 is a function? What does `{...f2}` mean for a function?

**Comment by calinn** [comment]
For functions {...f2} is a null object {}. f2={}. you're right it's wrong

**Pull request closed without merging**
