### PR TITLE
Enhancement/datatablematerialui

### PR DESCRIPTION
**Pull request by EloyID**
Split datatable in different files and added the same enhancements as core datatable

### CODE REVIEW

**Comment by EloyID** [comment]
What are the next steps for this PR ? Maybe wait the main Datatable to ve validated by Sacha or can other people start trying it ?

**Comment by eric-burel** [comment]
I just need to give a shot at the PR and merge if its ok
I'll test on Storybook + the starter

**Comment by eric-burel** [comment]
Is dependent on another PR?

**Comment by eric-burel** [comment]
To be continued in  #2558

**Pull request closed without merging**
