### PR TITLE
PrefilledProps for form nested arrays

### PR DESCRIPTION
**Pull request by ErikDakoda**
In SmartForms, add support for prefilled props for nested array elements

### CODE REVIEW

**Comment by eric-burel** [comment]
Hi, I am trying to unit test this but I don't get the expected behaviour.

If I write `<Form prefilledProps={{addresses: { street: "foobar" }} />` for example, the problem is that `{street: "foobar"}` will be the prefilled value for the whole array too, so rendering fails.


Maybe I misunderstood the expected syntax? Should it be `addresses.$` instead?

**Comment by eric-burel** [comment]
You can checkout the "ErikDakoda-FormNestedArrayPrefilledProps" branch on Vulcan, I've tested adding ".$" to the prop name to fill the array children instead of the array itself.

**Comment by ErikDakoda** [comment]
Hi @eric-burel! That looks like a good change. Thank you! Could you create a pull request for your version?

**Comment by eric-burel** [comment]
Yep it's merged, both having prefilled props for the whole array and for new items using ".$" will work. So you can even differentiate the first few values and subsequent values. Thanks!

**Pull request merged**
